### ISSUE TITLE
Display name need to be retrieved from Display attribute 

### ISSUE THREAD

**Issue by smurugavel** [IntertechInc/aa-validation-from-server#10]
Hello Rich.
I am trying to pull [Display(Name="A custom Name")] to aa-label and but couldn't get it to work.

I tested this in your latest source code and in my code, but couldn't make it to work.

In looking at the code for required attribute, it seems cursor hits convert method and second parameter (attr) seems to be Required attribute. This is correct.

RequiredConverter.cs
>> 
Convert(string propertyName, CustomAttributeData attr, StringBuilder jsonString, bool isFirstAttr, string resourceNamespace, string resourceAssemblyName)

but, the same attr is being used to get Display attribute and it fails. This attr is a Required Attribute and not Display Attribute.
<code>
var displayName = GetNamedArgumentValue(propertyName, attr, DataAnnotationConstants.Display);
</code>

Let me know.

Thanks

**Comment by richinator38** [comment]
Yes, there is a bug there...good catch!  I'll work on it.

**Comment by richinator38** [comment]
It is now fixed.

**Comment by smurugavel** [comment]
Thank you

Date: Mon, 27 Jul 2015 16:57:05 -0700
